In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn import linear_model
from sklearn.impute import SimpleImputer
from sklearn.ensemble import IsolationForest

In [82]:
Data=pd.read_csv("train.csv")

In [83]:
Data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [84]:
for call in Data.columns:
    print(call)

Id
MSSubClass
MSZoning
LotFrontage
LotArea
Street
Alley
LotShape
LandContour
Utilities
LotConfig
LandSlope
Neighborhood
Condition1
Condition2
BldgType
HouseStyle
OverallQual
OverallCond
YearBuilt
YearRemodAdd
RoofStyle
RoofMatl
Exterior1st
Exterior2nd
MasVnrType
MasVnrArea
ExterQual
ExterCond
Foundation
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinSF1
BsmtFinType2
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
Heating
HeatingQC
CentralAir
Electrical
1stFlrSF
2ndFlrSF
LowQualFinSF
GrLivArea
BsmtFullBath
BsmtHalfBath
FullBath
HalfBath
BedroomAbvGr
KitchenAbvGr
KitchenQual
TotRmsAbvGrd
Functional
Fireplaces
FireplaceQu
GarageType
GarageYrBlt
GarageFinish
GarageCars
GarageArea
GarageQual
GarageCond
PavedDrive
WoodDeckSF
OpenPorchSF
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
PoolQC
Fence
MiscFeature
MiscVal
MoSold
YrSold
SaleType
SaleCondition
SalePrice

In [85]:
Data.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [86]:
m = pd.DataFrame(Data.isnull().sum())
m.columns=["c"]
for i in range(len(m["c"])):
    if m["c"][i]>0:
        print(m.index[i],' ',m["c"][i])

LotFrontage   259
Alley   1369
MasVnrType   8
MasVnrArea   8
BsmtQual   37
BsmtCond   37
BsmtExposure   38
BsmtFinType1   37
BsmtFinType2   38
Electrical   1
FireplaceQu   690
GarageType   81
GarageYrBlt   81
GarageFinish   81
GarageQual   81
GarageCond   81
PoolQC   1453
Fence   1179
MiscFeature   1406

In [87]:
y = Data['SalePrice']
del Data['SalePrice']

## Seperating Numerical and Object type Data

In [88]:
Data_num = Data.select_dtypes(include=["float64", "int64"]).copy()
Data_obj = Data.select_dtypes(include ="object").copy()

In [89]:
del Data_num['Id']

In [90]:
n = pd.DataFrame(Data_num.isnull().sum())
n.columns=["c"]
for i in range(len(n["c"])):
    if n["c"][i]>0:
        print(n.index[i],' ',n["c"][i])

LotFrontage   259
MasVnrArea   8
GarageYrBlt   81

In [91]:
o = pd.DataFrame(Data_obj.isnull().sum())
o.columns=["c"]
for i in range(len(o["c"])):
    if o["c"][i]>0:
        print(o.index[i],' ',o["c"][i])

Alley   1369
MasVnrType   8
BsmtQual   37
BsmtCond   37
BsmtExposure   38
BsmtFinType1   37
BsmtFinType2   38
Electrical   1
FireplaceQu   690
GarageType   81
GarageFinish   81
GarageQual   81
GarageCond   81
PoolQC   1453
Fence   1179
MiscFeature   1406

In [11]:
imp = IterativeImputer()
Data_num = pd.DataFrame(imp.fit_transform(Data_num), columns = Data_num.columns)

In [12]:
Data_obj.replace(np.nan,'Unknown', inplace=True)

## Feature Scaling

In [13]:
scaler = MinMaxScaler()
Data_num = pd.DataFrame(scaler.fit_transform(Data_num), columns = Data_num.columns)

In [14]:
for i in Data_obj.columns:
    Data_obj[i]=Data_obj[i].astype('category')

In [15]:
for i in Data_obj.columns:
    print(Data_obj[i].value_counts())

RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64
Pave    1454
Grvl       6
Name: Street, dtype: int64
Unknown    1369
Grvl         50
Pave         41
Name: Alley, dtype: int64
Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64
AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64
Gtl    1382
Mod      65
Sev      13
Name: LandSlope, dtype: int64
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
SWISU       25
StoneBr     25
Blmngtn     17
MeadowV     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: Condition1, dtype: int64
Norm      1445
Feedr        6
RRNn         2
PosN         2
Artery       2
RRAn         1
RRAe         1
PosA         1
Name: Condition2, dtype: int64
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: RoofStyle, dtype: int64
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Roll          1
Metal         1
Membran       1
ClyTile       1
Name: RoofMatl, dtype: int64
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
Stone        2
BrkComm      2
ImStucc      1
CBlock       1
AsphShn      1
Name: Exterior1st, dtype: int64
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: Exterior2nd, dtype: int64
None       864
BrkFace    445
Stone      128
BrkCmn      15
Unknown      8
Name: MasVnrType, dtype: int64
TA    906
Gd    488
Ex     52
Fa     14
Name: ExterQual, dtype: int64
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: ExterCond, dtype: int64
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: Foundation, dtype: int64
TA         649
Gd         618
Ex         121
Unknown     37
Fa          35
Name: BsmtQual, dtype: int64
TA         1311
Gd           65
Fa           45
Unknown      37
Po            2
Name: BsmtCond, dtype: int64
No         953
Av         221
Gd         134
Mn         114
Unknown     38
Name: BsmtExposure, dtype: int64
Unf        430
GLQ        418
ALQ        220
BLQ        148
Rec        133
LwQ         74
Unknown     37
Name: BsmtFinType1, dtype: int64
Unf        1256
Rec          54
LwQ          46
Unknown      38
BLQ          33
ALQ          19
GLQ          14
Name: BsmtFinType2, dtype: int64
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: Heating, dtype: int64
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: HeatingQC, dtype: int64
Y    1365
N      95
Name: CentralAir, dtype: int64
SBrkr      1334
FuseA        94
FuseF        27
FuseP         3
Unknown       1
Mix           1
Name: Electrical, dtype: int64
TA    735
Gd    586
Ex    100
Fa     39
Name: KitchenQual, dtype: int64
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: Functional, dtype: int64
Unknown    690
Gd         380
TA         313
Fa          33
Ex          24
Po          20
Name: FireplaceQu, dtype: int64
Attchd     870
Detchd     387
BuiltIn     88
Unknown     81
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64
Unf        605
RFn        422
Fin        352
Unknown     81
Name: GarageFinish, dtype: int64
TA         1311
Unknown      81
Fa           48
Gd           14
Po            3
Ex            3
Name: GarageQual, dtype: int64
TA         1326
Unknown      81
Fa           35
Gd            9
Po            7
Ex            2
Name: GarageCond, dtype: int64
Y    1340
N      90
P      30
Name: PavedDrive, dtype: int64
Unknown    1453
Gd            3
Fa            2
Ex            2
Name: PoolQC, dtype: int64
Unknown    1179
MnPrv       157
GdPrv        59
GdWo         54
MnWw         11
Name: Fence, dtype: int64
Unknown    1406
Shed         49
Othr          2
Gar2          2
TenC          1
Name: MiscFeature, dtype: int64
WD       1267
New       122
COD        43
ConLD       9
ConLw       5
ConLI       5
CWD         4
Oth         3
Con         2
Name: SaleType, dtype: int64
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: SaleCondition, dtype: int64

In [16]:
Data_obj_onehot = Data_obj.copy()
for i in Data_obj.columns:
    Data_obj_onehot = pd.get_dummies(Data_obj_onehot, columns=[i], prefix_sep="_|_")

In [17]:
Data_obj_onehot

,MSZoning_|_C (all),MSZoning_|_FV,MSZoning_|_RH,MSZoning_|_RL,MSZoning_|_RM,Street_|_Grvl,Street_|_Pave,Alley_|_Grvl,Alley_|_Pave,Alley_|_Unknown,...,SaleType_|_ConLw,SaleType_|_New,SaleType_|_Oth,SaleType_|_WD,SaleCondition_|_Abnorml,SaleCondition_|_AdjLand,SaleCondition_|_Alloca,SaleCondition_|_Family,SaleCondition_|_Normal,SaleCondition_|_Partial
0,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
3,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,1,0,0,0,0,0
4,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1456,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1457,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1458,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1459,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0

In [18]:
Data_final = pd.concat([Data_num,Data_obj_onehot], axis=1, sort=False)

In [19]:
# isol = IsolationForest(max_samples=100, contamination = 0.1, random_state=42)
# isol.fit(Data_final)
# y_outliers = isol.predict(Data_final)

In [20]:
# for i in range(len(y_outliers)):
#     if y_outliers[i] == -1:
#         Data_final.drop(i,inplace = True)
#         y.drop(i,inplace=True)

In [21]:
Data_final.shape

(1460, 304)

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(Data_final, y, test_size =0.1, random_state=100)

In [23]:
X_train.shape

(1314, 304)

In [24]:
from sklearn.metrics import r2_score
from sklearn.metrics import max_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
def generate_model_report(y_actual, y_predicted):
    print("r2 score = ", r2_score(y_actual, y_predicted))
    print("Max Error = ", max_error(y_actual, y_predicted))
    print("Mean Absolute Erroe = ", mean_absolute_error(y_actual, y_predicted))
    print("Mean Squared Error = ", mean_squared_error(y_actual, y_predicted))
    print("Mean squared logarithmic error = ", mean_squared_log_error(y_actual, y_predicted))
    pass

In [25]:
ols = RandomForestRegressor()
model = ols.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
generate_model_report(Y_test, Y_pred)

r2 score =  0.8525109173736988
Max Error =  163190.79
Mean Absolute Erroe =  17751.043219178082
Mean Squared Error =  842933157.7649173
Mean squared logarithmic error =  0.027739898175064417

In [26]:
ols = DecisionTreeRegressor()
model = ols.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
generate_model_report(Y_test, Y_pred)

r2 score =  0.7455920578812395
Max Error =  236500.0
Mean Absolute Erroe =  22106.424657534248
Mean Squared Error =  1453998399.0136986
Mean squared logarithmic error =  0.036512295125965176

In [27]:
las = Lasso()
model = las.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
generate_model_report(Y_test, Y_pred)

r2 score =  0.8652580121717859
Max Error =  135151.7675340143
Mean Absolute Erroe =  18784.29600891361
Mean Squared Error =  770080654.5209641
Mean squared logarithmic error =  0.04213317098818071

c:\users\win10\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:474: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 98741719168.91446, tolerance: 836073583.0301565
  model = cd_fast.enet_coordinate_descent(

In [73]:
rid = Ridge()
model = rid.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
generate_model_report(Y_test, Y_pred)

r2 score =  0.8665886721037235
Max Error =  136864.3107921998
Mean Absolute Erroe =  18667.504428645127
Mean Squared Error =  762475634.8248188
Mean squared logarithmic error =  0.03338389267089074

In [29]:
Data_Test=pd.read_csv("test.csv")

In [30]:
Data_Test.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
Length: 80, dtype: object

In [31]:
n = pd.DataFrame(Data_Test.isnull().sum())
n.columns=["c"]

for i in range(len(n["c"])):
    if n["c"][i]>0:
        print(m.index[i],' ',n["c"][i])

MSZoning   4
LotFrontage   227
Alley   1352
Utilities   2
Exterior1st   1
Exterior2nd   1
MasVnrType   16
MasVnrArea   15
BsmtQual   44
BsmtCond   45
BsmtExposure   44
BsmtFinType1   42
BsmtFinSF1   1
BsmtFinType2   42
BsmtFinSF2   1
BsmtUnfSF   1
TotalBsmtSF   1
BsmtFullBath   2
BsmtHalfBath   2
KitchenQual   1
Functional   2
FireplaceQu   730
GarageType   76
GarageYrBlt   78
GarageFinish   78
GarageCars   1
GarageArea   1
GarageQual   78
GarageCond   78
PoolQC   1456
Fence   1169
MiscFeature   1408
SaleType   1

In [32]:
DT_num = Data_Test.select_dtypes(include=["float64", "int64"]).copy()
DT_obj = Data_Test.select_dtypes(include ="object").copy()

In [33]:
I = DT_num['Id']
del DT_num['Id']

In [34]:
DT_obj.replace(np.nan,'Unknown', inplace=True)

In [35]:
DT_num = pd.DataFrame(imp.transform(DT_num), columns = DT_num.columns)

In [36]:
DT_num = pd.DataFrame(scaler.transform(DT_num), columns = DT_num.columns)

In [37]:
for i in DT_obj.columns:
    DT_obj[i]=DT_obj[i].astype('category')

In [38]:
for i in DT_obj.columns:
    print(DT_obj[i].value_counts())

RL         1114
RM          242
FV           74
C (all)      15
RH           10
Unknown       4
Name: MSZoning, dtype: int64
Pave    1453
Grvl       6
Name: Street, dtype: int64
Unknown    1352
Grvl         70
Pave         37
Name: Alley, dtype: int64
Reg    934
IR1    484
IR2     35
IR3      6
Name: LotShape, dtype: int64
Lvl    1311
HLS      70
Bnk      54
Low      24
Name: LandContour, dtype: int64
AllPub     1457
Unknown       2
Name: Utilities, dtype: int64
Inside     1081
Corner      248
CulDSac      82
FR2          38
FR3          10
Name: LotConfig, dtype: int64
Gtl    1396
Mod      60
Sev       3
Name: LandSlope, dtype: int64
NAmes      218
OldTown    126
CollgCr    117
Somerst     96
Edwards     94
NridgHt     89
Gilbert     86
Sawyer      77
SawyerW     66
Mitchel     65
NWAmes      58
IDOTRR      56
Crawfor     52
BrkSide     50
Timber      34
NoRidge     30
StoneBr     26
SWISU       23
MeadowV     20
ClearCr     16
BrDale      14
NPkVill     14
Veenker     13
Blmngtn     11
Blueste      8
Name: Neighborhood, dtype: int64
Norm      1251
Feedr       83
Artery      44
RRAn        24
PosN        20
RRAe        17
PosA        12
RRNn         4
RRNe         4
Name: Condition1, dtype: int64
Norm      1444
Feedr        7
PosA         3
Artery       3
PosN         2
Name: Condition2, dtype: int64
1Fam      1205
TwnhsE     113
Duplex      57
Twnhs       53
2fmCon      31
Name: BldgType, dtype: int64
1Story    745
2Story    427
1.5Fin    160
SLvl       63
SFoyer     46
2.5Unf     13
1.5Unf      5
Name: HouseStyle, dtype: int64
Gable      1169
Hip         265
Gambrel      11
Flat          7
Mansard       4
Shed          3
Name: RoofStyle, dtype: int64
CompShg    1442
Tar&Grv      12
WdShake       4
WdShngl       1
Name: RoofMatl, dtype: int64
VinylSd    510
MetalSd    230
HdBoard    220
Wd Sdng    205
Plywood    113
CemntBd     65
BrkFace     37
WdShing     30
AsbShng     24
Stucco      18
BrkComm      4
Unknown      1
CBlock       1
AsphShn      1
Name: Exterior1st, dtype: int64
VinylSd    510
MetalSd    233
HdBoard    199
Wd Sdng    194
Plywood    128
CmentBd     66
Wd Shng     43
BrkFace     22
Stucco      21
AsbShng     18
Brk Cmn     15
ImStucc      5
CBlock       2
Unknown      1
Stone        1
AsphShn      1
Name: Exterior2nd, dtype: int64
None       878
BrkFace    434
Stone      121
Unknown     16
BrkCmn      10
Name: MasVnrType, dtype: int64
TA    892
Gd    491
Ex     55
Fa     21
Name: ExterQual, dtype: int64
TA    1256
Gd     153
Fa      39
Ex       9
Po       2
Name: ExterCond, dtype: int64
PConc     661
CBlock    601
BrkTil    165
Slab       25
Stone       5
Wood        2
Name: Foundation, dtype: int64
TA         634
Gd         591
Ex         137
Fa          53
Unknown     44
Name: BsmtQual, dtype: int64
TA         1295
Fa           59
Gd           57
Unknown      45
Po            3
Name: BsmtCond, dtype: int64
No         951
Av         197
Gd         142
Mn         125
Unknown     44
Name: BsmtExposure, dtype: int64
GLQ        431
Unf        421
ALQ        209
Rec        155
BLQ        121
LwQ         80
Unknown     42
Name: BsmtFinType1, dtype: int64
Unf        1237
Rec          51
Unknown      42
LwQ          41
BLQ          35
ALQ          33
GLQ          20
Name: BsmtFinType2, dtype: int64
GasA    1446
GasW       9
Wall       2
Grav       2
Name: Heating, dtype: int64
Ex    752
TA    429
Gd    233
Fa     43
Po      2
Name: HeatingQC, dtype: int64
Y    1358
N     101
Name: CentralAir, dtype: int64
SBrkr    1337
FuseA      94
FuseF      23
FuseP       5
Name: Electrical, dtype: int64
TA         757
Gd         565
Ex         105
Fa          31
Unknown      1
Name: KitchenQual, dtype: int64
Typ        1357
Min2         36
Min1         34
Mod          20
Maj1          5
Maj2          4
Unknown       2
Sev           1
Name: Functional, dtype: int64
Unknown    730
Gd         364
TA         279
Fa          41
Po          26
Ex          19
Name: FireplaceQu, dtype: int64
Attchd     853
Detchd     392
BuiltIn     98
Unknown     76
Basment     17
2Types      17
CarPort      6
Name: GarageType, dtype: int64
Unf        625
RFn        389
Fin        367
Unknown     78
Name: GarageFinish, dtype: int64
TA         1293
Unknown      78
Fa           76
Gd           10
Po            2
Name: GarageQual, dtype: int64
TA         1328
Unknown      78
Fa           39
Po            7
Gd            6
Ex            1
Name: GarageCond, dtype: int64
Y    1301
N     126
P      32
Name: PavedDrive, dtype: int64
Unknown    1456
Ex            2
Gd            1
Name: PoolQC, dtype: int64
Unknown    1169
MnPrv       172
GdPrv        59
GdWo         58
MnWw          1
Name: Fence, dtype: int64
Unknown    1408
Shed         46
Gar2          3
Othr          2
Name: MiscFeature, dtype: int64
WD         1258
New         117
COD          44
ConLD        17
CWD           8
Oth           4
ConLI         4
ConLw         3
Con           3
Unknown       1
Name: SaleType, dtype: int64
Normal     1204
Partial     120
Abnorml      89
Family       26
Alloca       12
AdjLand       8
Name: SaleCondition, dtype: int64

In [39]:
DT_obj_onehot = DT_obj.copy()
for i in DT_obj.columns:
    DT_obj_onehot = pd.get_dummies(DT_obj_onehot, columns=[i], prefix_sep="_|_")

In [40]:
DT_obj_onehot

,MSZoning_|_C (all),MSZoning_|_FV,MSZoning_|_RH,MSZoning_|_RL,MSZoning_|_RM,MSZoning_|_Unknown,Street_|_Grvl,Street_|_Pave,Alley_|_Grvl,Alley_|_Pave,...,SaleType_|_New,SaleType_|_Oth,SaleType_|_Unknown,SaleType_|_WD,SaleCondition_|_Abnorml,SaleCondition_|_AdjLand,SaleCondition_|_Alloca,SaleCondition_|_Family,SaleCondition_|_Normal,SaleCondition_|_Partial
0,0,0,1,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
4,0,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1455,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
1456,0,0,0,1,0,0,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
1457,0,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1458,0,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0

In [41]:
DT_final = pd.concat([DT_num,DT_obj_onehot], axis=1, sort=False)

In [42]:
DT_final["new1"]=0
DT_final["new2"]=0
DT_final["new3"]=0
DT_final["new4"]=0
DT_final["new5"]=0
DT_final["new6"]=0
DT_final["new7"]=0
DT_final["new8"]=0
DT_final["new9"]=0
DT_final["new10"]=0
DT_final["new11"]=0
DT_final["new12"]=0

In [43]:
DT_final.shape

(1459, 304)

In [75]:
Y = rid.predict(DT_final)
prediction = pd.DataFrame(Y)
sub_df = pd.read_csv('sample_submission.csv')
datasets=pd.concat([sub_df['Id'],prediction],axis=1)
datasets.columns=['Id', 'SalePrice']
datasets.to_csv('sample_submission.csv', index=False)

In [77]:
sub_df.head()

     Id      SalePrice
0  1461  196317.093820
1  1462  141406.120059
2  1463  214001.051882
3  1464  206025.668748
4  1465  255025.469007